#pragma once

#define DIGITIZER_MOTION_PIN GP26
#define DIGITIZER_MOTION_PIN_ACTIVE_LOW yes
#define PROCYON_57_80
#define MXT_SWITCH_XY
#define MXT_INVERT_Y
#define I2C1_CLOCK_SPEED 1000000
#define I2C_DRIVER I2CD1
#define I2C1_SDA_PIN GP2
#define I2C1_SCL_PIN GP3